spring:
  jpa:
    database: postgresql
    driver-class-name: org.postgresql.Driver
  datasource:
   url: jdbc:postgresql://localhost:5055/ccd_data?stringtype=unspecified
   username: ccd
   password: ccd
idam:
  api:
    url: ${IDAM_API_URL:http://localhost:5000}
  client:
    id: ${IDAM_MIGRATION_ID:test}
    secret: ${IDAM_MIGRATION_SECRET:test_secret}
    redirect_uri: ${IDAM_MIGRATION_URI:http://test}
    scope: openid roles profile manage-user
